### ISSUE TITLE
New pack Creation - Crashes

### ISSUE THREAD

**Issue by power-spike** [Darkhax-Minecraft/Game-Stages#19]
Greetings, 

Installing the latest version of Game stages is crashing.

java.lang.NoClassDefFoundError: net/darkhax/gamestages/event/GameStageEvent$ClientSync

basically a fresh install of mods, complaining about stages not found. Have had to downgrade to 1.0.86,  which has also forced a full downgrade of recipe stages to 1.0.8 - because the 1.1 and 1.1.1 of recipe stages require a V2+ verison of game stages.

Version 2.0.91

Crash Log:- https://pastebin.com/ZFFb8aLv

**Comment by darkhax** [comment]
GameStages 2 is a complete rewrite of the API to be more efficient. All addons need to update to work with the new changes. All the official addons are already updated to work on 2.0, and their versions are labeled as 2.0 as well. Looking at your crash log you are using outdated mods. 

- DimensionStages 1.0.18
- ItemStages 1.0.33

If you continue to get this issue after updating those, then there is another addon that you have not updated to latest.
